### ISSUE TITLE
部分翻译不一致

### ISSUE THREAD

**Issue by Yukiniro** [rollup/rollup-docs-cn#28]
### Documentation is

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not sure?

### Please Explain in Detail...

目前中文翻译中对 you 有你和您，对 treeshaking 有除屑优化和树摇优化，是不是统一一下比较好

### Your Proposal for Changes

you 对应 你
treeshaking 对应 树摇或者不翻译

**Comment by waynzh** [comment]
同意约定常用词。另外，看起来还需要统一下其他的贡献规范，比如格式问题。
我看你已经提交一个大改动 PR，可以先参考 [Vite 中文文档翻译规范](https://github.com/vitejs/docs-cn/wiki/%E5%90%88%E4%BD%9C%E8%A7%84%E8%8C%83) 再校验下格式问题，比如删除了一些空格。

对于提到的这两个例子，可以先约定 `you` 为 `你`，`treeshaking ` 为 `除屑优化`，其余的名词可以先保持现状，后续有词汇约定后再统一更改。如果有精力欢迎更新 PR 哈。

**Comment by Yukiniro** [comment]
好的，我尽快会更新 PR

**Comment by ShenQingchuan** [comment]
cc @waynzh @Yukiniro 
该 issue 还有后续问题吗？如果没有是不是可以认为是 close by #27  了？
