### ISSUE TITLE
代码块复制按钮样式问题

### ISSUE THREAD

**Issue by btea** [rollup/rollup-docs-cn#29]
### Rollup Version

latest

### Operating System (or Browser)

Chrome

### Link To Reproduction

https://rollup-docs-cn.netlify.app/introduction/

### Expected Behaviour

样式正确

参考这个 https://github.com/rollup/rollup/pull/4925

### Actual Behaviour

样式错位

**Comment by waynzh** [comment]
thanks！
在下次同步英文主仓库代码后会修复。
